### ISSUE TITLE
main.c issues

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#1]
1. int set_file_content(const char *filename, char *content, long content_size):
   a. signed content_size does not make sense; suggest using unsigned value;
   b. fwrite declaration: size_t fwrite( const void \* ptrvoid, size_t size, size_t count, FILE \* filestream)
   you have mixed up the 2nd and the 3rd parameters in your code;
   c. suggest using "const char *content";
   d. suggest returning the return value of fwrite() call.
2. int get_file_content(const char *filename, char *content, long *max_content_size):
   a. same as above - suggest using unsigned max_content_size;
   b. what's the point of this assignment?
   long fsize = ftell(f);
   long read_size = fsize;
   c. fread() parameters are also mixed up;
   d. you can write the fread() call return value into *max_content_size.

**Comment by dmitrii-eremin** [comment]
All on all items accepted.
