### ISSUE TITLE
Confusing function names

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#10]
The description and the function name combination is confusing - I'd expect jfes_is_null() to return non-zero value if null, and zero otherwise. But, according to the description, the name should be more like jfes_is_not_null().

``` c
/**
    Analyzes input string on the subject of whether it is null.
    \param[in]      data                Input string.
    \param[in]      length              Optional. Length of the input string.
                                        You can pass 0, if string is zero-terminated.
    \return         Zero, if input string not null. Otherwise anything.
*/
static int jfes_is_null(const char *data, jfes_size_t length) {
```

Same for

``` c
static int jfes_is_boolean(const char *data, jfes_size_t length)
```

**Comment by NeonMercury** [comment]
Oops, function have incorrect description.
```
/**
    Analyzes input string on the subject of whether it is null.
    \param[in]      data                Input string.
    \param[in]      length              Optional. Length of the input string.
                                        You can pass 0, if string is zero-terminated.
    \return         Zero, if input string not null. Otherwise anything.
*/
static int jfes_is_null(const char *data, jfes_size_t length) {
    if (!data) {
        return 0;
    }

    if (length == 0) {
        length = jfes_strlen(data);
    }

    return  jfes_memcmp(data, "null", jfes_strlen("null")) == 0;
}
```
According to the source code of the function, it'll return zero when `data` is not `"null"`, and one otherwise.

So, I just need to correct the function description. Thanks.

**Comment by dmitrii-eremin** [comment]
The functions returns zero, if data isn't equals to `"null"`.
I think, the description is correct, isn't it?

**Comment by f2404** [comment]
Yes, the description is correct.
The function name, however, makes one think that a non-zero value will be returned if data equals to "null". For example, isdigit(int c) returns non-zero value if 'c' is digit.
Similarly, the function named jfes_is_null() should return non-zero if data is "null". But now it's behaving in the opposite way.

**Comment by dmitrii-eremin** [comment]
Function definition is:

```
/**
    Analyzes input string on the subject of whether it is null.
    \param[in]      data                Input string.
    \param[in]      length              Optional. Length of the input string.
                                        You can pass 0, if string is zero-terminated.
    \return         Zero, if input string not null. Otherwise anything.
*/
static int jfes_is_null(const char *data, jfes_size_t length) {
    if (!data) {
        return 0;
    }

    if (length == 0) {
        length = jfes_strlen(data);
    }

    return  jfes_memcmp(data, "null", jfes_strlen("null")) == 0;
}
```

Lets consider two cases.
- First case: `data = "some string"`.
  `jfes_memcmp(data, "null", jfes_strlen("null"))` will return non-zero value. Non-zero value isn't equals to 0. Therefore `<smth> == 0 -> 0` and the function returns 0.
- Second case: `data = "null"`.
  `jfes_memcmp(data, "null", jfes_strlen("null"))` will return zero value. 0 is equals to 0. Therefore `0 == 0 -> 1` and the function returns 1.

Thus, `jfes_is_null` works like `isdigit`. It returns non-zero value, if `data` is `"null"`.

**Comment by f2404** [comment]
Ok, agree. I got totally confused. Sorry.

One thing that is still bothering me is that I get 0 if I pass data==NULL. This is understood because data is not "null" in this case. But I think, the description should better be saying

```
\return         Zero, if input string equals to "null". Otherwise anything.
```

Thanks.

**Comment by dmitrii-eremin** [comment]
Ok, in the next commit I'll take "null" in quotes. It'll be better this way.
