### ISSUE TITLE
jfes_integer_to_string: static buffer

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#12]
I don't like the idea of using a static buffer and returning a pointer to its contents.
This results in the possibility of data corruption when jfes_integer_to_string() is called multiple times. Why don't allocate the memory dynamically?

``` c
char *jfes_integer_to_string(int value) {
    static char buf[JFES_MAX_DIGITS + 3];
    char *p = &buf[0] + JFES_MAX_DIGITS + 2;
    ...
    return p;
}
```

**Comment by dmitrii-eremin** [comment]
Because in this case, it's not necessary to free allocated memory. I think, it's better to do this way. I think I should to add a remark to the function description about multiple using.

**Comment by f2404** [comment]
I just don't like that if you can unintentionally corrupt your data if you use the code like below (http://ideone.com/6NJyn7):

``` c
    char *c1 = NULL, *c2 = NULL;
    c1 = jfes_integer_to_string(123);
    printf("c=%s c2=%s\n", c1, c2);
    c2 = jfes_integer_to_string(765);
    printf("c=%s c2=%s\n", c1, c2);
    strcpy(c1, "abc");
    printf("c=%s c2=%s\n", c1, c2);
```

In such case, you'll have c1 corrupted when assigning c2; and then c2 corrupted by strcpy to c1.

**Comment by dmitrii-eremin** [comment]
If my memory serves me, one of the standard implementations of the `itoa` works this way.
Memory must be allocated and freed in the same scope.
If you need the returned data, then copy it. If you don't need it, forget it.

**Comment by f2404** [comment]
Not sure about itoa() but strerror() does work this way, correct.
What about multi-threading? Is jfes going to support it?

**Comment by dmitrii-eremin** [comment]
Yes, I think in the future I'll add the `jfes_(integer/double)_to_string_r()` function, like `strerror_r()` to support multithreading.

**Comment by f2404** [comment]
Okay.
