### ISSUE TITLE
jfes.c issues part 1

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#2]
1. You need to verify the pointers against NULL before dereferencing them in jfes_memcmp() and jfes_memcpy().
2. static const void _jfes_memcpy(const void *dst, const void *src, jfes_size_t count)
   *dst should not be const;
   return void_ should not be const as well.
3. jfes_allocate_string(): what if malloc() fails? still returning success?
4. I guess, pointers to jfes_malloc, jfes_free, jfes_memcpy functions should be verified against NULL before being called.
5. jfes_is_null(const char *data, jfes_size_t length), jfes_is_boolean(const char *data, jfes_size_t length)
   Why do you need length parameter here? Better calculate data length within the function.

**Comment by dmitrii-eremin** [comment]
1. Accepted.
2. Accepted.
3. Accepted.
4. C99 Standard says about memcpy:

> If an argument to a function has an invalid value (such as a value outside the domain of the function, or a pointer outside the address space of the program, or a null pointer, or a pointer to non-modifiable storage when the corresponding parameter is not const-qualified) or a type (after promotion) not expected by a function with variable number of arguments, the behavior is undefined.

So, I don't sure I need to check this.
5. Accepted. But I'll make this arguments optional, as in many `jfes_...` functions. You can pass zero and then length will be calculated by `jfes_strlen()`.
