### ISSUE TITLE
Verify config->jfes_malloc and config->jfes_free against NULL

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#5]
Need to verify that config->jfes_malloc() or config->jfes_free() function pointers are not NULL before calling them.
E.g.
if (config->jfes_malloc)
    str->data = (char*)config->jfes_malloc(str->size);

**Comment by dmitrii-eremin** [comment]
I relied on the fact, that the configuration object is set up correctly and the program will fall if there is something wrong. But it is more correct to return an error.  
You're right, thank you.
