### ISSUE TITLE
Enum and struct names overridden

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#7]
Some of the enum values are overridden by the struct names in jfes.h:

``` c
    jfes_string             = 0x05,             /**< String token type. */
    jfes_array              = 0x06,             /**< Array token type. */
    jfes_object             = 0x07,             /**< Object token type. */
```

and

``` c
typedef struct jfes_string {
typedef struct jfes_array {
typedef struct jfes_object {
```

Suggest renaming them, e.g.

``` c
typedef struct _jfes_string_t {
...
} jfes_string_t;
```

**Comment by dmitrii-eremin** [comment]
Thank you. `..._t` at the end of the name of the structure means `typedef`. Therefore, I don't think we should to rename the structures.  
I think, I will rename the enum values closer to its original meaning.  Something like:

```
jfes_type_string             = 0x05,             /**< String token type. */
jfes_type_array              = 0x06,             /**< Array token type. */
jfes_type_object             = 0x07,             /**< Object token type. */
```

**Comment by f2404** [comment]
Actually, we can typedef an anonymous struct, e.g.

``` c
typedef struct {
...
} jfes_string_t;
```

This would also solve the issue with minimal changes.

**Comment by dmitrii-eremin** [comment]
Thanks for the suggestion, but I still propose to rename enum values, because it will be ideologically correct. JFES is not so widespread, the release was a few days ago and it's still in pre-alpha stage. So, I think I just rename the values.

It was a mistake to give so common names to the enum values.

**Comment by f2404** [comment]
Ok, sure, as you wish.
