### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by f2404** [NeonMercury/jfes#8]
Please either create Makefile, or put building instructions into README.

**Comment by dmitrii-eremin** [comment]
The JFES is not necessary to build, it's enough to add the files to the project, but I'll put building instructions into `README.md`. Thanks.

**Comment by f2404** [comment]
I think you should at least show how to build a working example.

**Comment by dmitrii-eremin** [comment]
Developers can see working examples [here](https://github.com/NeonMercury/jfes/tree/master/examples). And this is in `README.md` in section _Examples_.
For more detailed understanding of JFES I think that enough to clone this repo and run it.

**Comment by f2404** [comment]
Ok, I run 'gcc main.c' and get the following errors:

```
$ gcc main.c 
In file included from main.c:8:0:
jfes.h:40:24: error: expected ‘)’ before ‘*’ token
 typedef void *(__cdecl *jfes_malloc_t)(jfes_size_t);
                        ^
jfes.h:43:23: error: expected ‘)’ before ‘*’ token
 typedef void (__cdecl *jfes_free_t)(void*);
                       ^
jfes.h:80:5: error: unknown type name ‘jfes_malloc_t’
     jfes_malloc_t           jfes_malloc;        /**< Memory allocation function. */
     ^
jfes.h:81:5: error: unknown type name ‘jfes_free_t’
     jfes_free_t             jfes_free;          /**< Memory deallocation function. */
     ^
```

Adding jfes.c ('gcc main.c jfes.c') just produces much more errors.
Looks like "__cdecl" is not allowing the code to be built with gcc. I really think that building instructions are necessary.

**Comment by dmitrii-eremin** [comment]
Wow, thank you.
I didn't try to compile JFES with the gcc. I will work later on crossplatform compiling and some building instructions, thanks!.
